use crate::command::move_command::Move;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum Edit {
    Insert(char),
    InsertNewline,
    Delete,
    DeleteBackward,
    DeleteToEnd,
    DeleteWholeLine,
    DeleteWord,
    DeleteWordBackward,
    DeleteToNextWordStart,
    DeleteToLineStart,
    DeleteLine,
    DeleteRangeToMove(Move),
    YankRangeToMove(Move),
    ChangeRangeToMove(Move),
    Replace(char),
    YankLine,
    Paste,
    PasteAbove,
    Undo,
    Redo,
    JoinLines,
    ToggleCase,
    RepeatLastEdit,
    Indent,
    Deindent,
    DeleteSelection,
    YankSelection,
    ToggleCaseSelection,
    ReplaceWithYank,
    YankInnerWord,
}
