use editor_core::key::Key;

/// 将 egui 按键 + 修饰键转换为统一 Key 枚举。
pub fn egui_to_key(egui_key: egui::Key, modifiers: egui::Modifiers) -> Option<Key> {
    // Ctrl 组合键优先处理
    if modifiers.ctrl {
        return match egui_key {
            egui::Key::Q => Some(Key::Ctrl('q')),
            egui::Key::S => Some(Key::Ctrl('s')),
            egui::Key::F => Some(Key::Ctrl('f')),
            egui::Key::R => Some(Key::Ctrl('r')),
            egui::Key::D => Some(Key::Ctrl('d')),
            egui::Key::U => Some(Key::Ctrl('u')),
            egui::Key::W => Some(Key::Ctrl('w')),
            egui::Key::H => Some(Key::CtrlBackspace),
            egui::Key::Backspace => Some(Key::CtrlBackspace),
            egui::Key::Delete => Some(Key::CtrlDelete),
            egui::Key::OpenBracket => Some(Key::Escape),
            _ => None,
        };
    }

    // Shift 修饰键
    if modifiers.shift {
        return match egui_key {
            egui::Key::I => Some(Key::Shift('I')),
            egui::Key::A => Some(Key::Shift('A')),
            egui::Key::S => Some(Key::Shift('S')),
            egui::Key::C => Some(Key::Shift('C')),
            egui::Key::D => Some(Key::Shift('D')),
            egui::Key::X => Some(Key::Shift('X')),
            egui::Key::O => Some(Key::Shift('O')),
            egui::Key::V => Some(Key::Shift('V')),
            egui::Key::Y => Some(Key::Shift('Y')),
            egui::Key::P => Some(Key::Shift('P')),
            egui::Key::N => Some(Key::Shift('N')),
            egui::Key::J => Some(Key::Shift('J')),
            egui::Key::T => Some(Key::Shift('T')),
            egui::Key::F => Some(Key::Shift('F')),
            egui::Key::G => Some(Key::Shift('G')),
            egui::Key::W => Some(Key::Shift('W')),
            egui::Key::E => Some(Key::Shift('E')),
            egui::Key::B => Some(Key::Shift('B')),
            egui::Key::Semicolon => Some(Key::Shift(':')),
            egui::Key::Slash => Some(Key::Shift('?')),
            egui::Key::Num8 => Some(Key::Shift('*')),
            egui::Key::Num3 => Some(Key::Shift('#')),
            egui::Key::Num5 => Some(Key::Shift('%')),
            egui::Key::Backtick => Some(Key::Shift('~')),
            egui::Key::Num4 => Some(Key::Shift('$')),
            egui::Key::Num6 => Some(Key::Shift('^')),
            egui::Key::Comma => Some(Key::Shift('<')),
            egui::Key::Period => Some(Key::Shift('>')),
            _ => None,
        };
    }

    // 无修饰键
    match egui_key {
        egui::Key::Escape => Some(Key::Escape),
        egui::Key::Enter => Some(Key::Enter),
        egui::Key::Tab => Some(Key::Tab),
        egui::Key::Backspace => Some(Key::Backspace),
        egui::Key::Delete => Some(Key::Delete),
        egui::Key::ArrowUp => Some(Key::Up),
        egui::Key::ArrowDown => Some(Key::Down),
        egui::Key::ArrowLeft => Some(Key::Left),
        egui::Key::ArrowRight => Some(Key::Right),
        egui::Key::PageUp => Some(Key::PageUp),
        egui::Key::PageDown => Some(Key::PageDown),
        egui::Key::Home => Some(Key::Home),
        egui::Key::End => Some(Key::End),
        egui::Key::Space => Some(Key::Char(' ')),
        egui::Key::Semicolon => Some(Key::Char(';')),
        egui::Key::Comma => Some(Key::Char(',')),
        egui::Key::Period => Some(Key::Char('.')),
        egui::Key::Slash => Some(Key::Char('/')),
        egui::Key::Backtick => Some(Key::Char('`')),
        egui::Key::Minus => Some(Key::Char('-')),
        egui::Key::Equals => Some(Key::Char('=')),
        egui::Key::OpenBracket => Some(Key::Char('[')),
        egui::Key::CloseBracket => Some(Key::Char(']')),
        egui::Key::Backslash => Some(Key::Char('\\')),
        egui::Key::Quote => Some(Key::Char('\'')),
        // 数字键
        egui::Key::Num0 => Some(Key::Char('0')),
        egui::Key::Num1 => Some(Key::Char('1')),
        egui::Key::Num2 => Some(Key::Char('2')),
        egui::Key::Num3 => Some(Key::Char('3')),
        egui::Key::Num4 => Some(Key::Char('4')),
        egui::Key::Num5 => Some(Key::Char('5')),
        egui::Key::Num6 => Some(Key::Char('6')),
        egui::Key::Num7 => Some(Key::Char('7')),
        egui::Key::Num8 => Some(Key::Char('8')),
        egui::Key::Num9 => Some(Key::Char('9')),
        // 字母键（显式映射）
        egui::Key::A => Some(Key::Char('a')),
        egui::Key::B => Some(Key::Char('b')),
        egui::Key::C => Some(Key::Char('c')),
        egui::Key::D => Some(Key::Char('d')),
        egui::Key::E => Some(Key::Char('e')),
        egui::Key::F => Some(Key::Char('f')),
        egui::Key::G => Some(Key::Char('g')),
        egui::Key::H => Some(Key::Char('h')),
        egui::Key::I => Some(Key::Char('i')),
        egui::Key::J => Some(Key::Char('j')),
        egui::Key::K => Some(Key::Char('k')),
        egui::Key::L => Some(Key::Char('l')),
        egui::Key::M => Some(Key::Char('m')),
        egui::Key::N => Some(Key::Char('n')),
        egui::Key::O => Some(Key::Char('o')),
        egui::Key::P => Some(Key::Char('p')),
        egui::Key::Q => Some(Key::Char('q')),
        egui::Key::R => Some(Key::Char('r')),
        egui::Key::S => Some(Key::Char('s')),
        egui::Key::T => Some(Key::Char('t')),
        egui::Key::U => Some(Key::Char('u')),
        egui::Key::V => Some(Key::Char('v')),
        egui::Key::W => Some(Key::Char('w')),
        egui::Key::X => Some(Key::Char('x')),
        egui::Key::Y => Some(Key::Char('y')),
        egui::Key::Z => Some(Key::Char('z')),
        // 功能键
        egui::Key::F1 => Some(Key::F(1)),
        egui::Key::F2 => Some(Key::F(2)),
        egui::Key::F3 => Some(Key::F(3)),
        egui::Key::F4 => Some(Key::F(4)),
        egui::Key::F5 => Some(Key::F(5)),
        egui::Key::F6 => Some(Key::F(6)),
        egui::Key::F7 => Some(Key::F(7)),
        egui::Key::F8 => Some(Key::F(8)),
        egui::Key::F9 => Some(Key::F(9)),
        egui::Key::F10 => Some(Key::F(10)),
        egui::Key::F11 => Some(Key::F(11)),
        egui::Key::F12 => Some(Key::F(12)),
        _ => None,
    }
}
